vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/1/1.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 1
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/2/2.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 2
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/3/3.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 3
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/4/4.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 4
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/5/5.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 5
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/6/6.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 6
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/7/7.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 7
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/8/8.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 8
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/9/9.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 9
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/10/10.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 10
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/11/11.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 11
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/12/12.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 12
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/13/13.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 13
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/14/14.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 14
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/15/15.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 15
