vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/1/1.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 1
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/2/2.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 2
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/3/3.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 3
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/4/4.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 4
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/5/5.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 5
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/6/6.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 6
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/7/7.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 7
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/8/8.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 8
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/9/9.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 9
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/10/10.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 10
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/11/11.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 11
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/12/12.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 12
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/13/13.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 13
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/14/14.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 14
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/15/15.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 15
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/16/16.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 16
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/17/17.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 17
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/18/18.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 18
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/19/19.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 19
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/20/20.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 20
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/21/21.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 21
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/22/22.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 22
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/23/23.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 23
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/24/24.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 24
vmrun -gu cas -gp cas runProgramInGuest "E:/Virtual Machine/25/25.vmx" -activeWindow -interactive -nowait "Z:/Project Python/Auto-Clicker/ressources/Batch_Files/AC.bat" 25
