"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\1\1.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\2\2.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\3\3.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\4\4.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\5\5.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\6\6.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\7\7.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\8\8.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\9\9.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\10\10.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\11\11.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\12\12.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\13\13.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\14\14.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\15\15.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\16\16.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\17\17.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\18\18.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\19\19.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\20\20.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\21\21.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\22\22.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\23\23.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\24\24.vmx"

"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\1\1.vmx" linked -cloneName="1"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\2\2.vmx" linked -cloneName="2"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\3\3.vmx" linked -cloneName="3"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\4\4.vmx" linked -cloneName="4"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\5\5.vmx" linked -cloneName="5"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\6\6.vmx" linked -cloneName="6"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\7\7.vmx" linked -cloneName="7"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\8\8.vmx" linked -cloneName="8"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\9\9.vmx" linked -cloneName="9"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\10\10.vmx" linked -cloneName="10"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\11\11.vmx" linked -cloneName="11"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\12\12.vmx" linked -cloneName="12"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\13\13.vmx" linked -cloneName="13"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\14\14.vmx" linked -cloneName="14"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\15\15.vmx" linked -cloneName="15"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\16\16.vmx" linked -cloneName="16"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\17\17.vmx" linked -cloneName="17"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\18\18.vmx" linked -cloneName="18"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\19\19.vmx" linked -cloneName="19"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\20\20.vmx" linked -cloneName="20"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\21\21.vmx" linked -cloneName="21"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\22\22.vmx" linked -cloneName="22"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\23\23.vmx" linked -cloneName="23"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\May Ao Chuan\Windows 7 x64.vmx" "E:\Virtual Machine\24\24.vmx" linked -cloneName="24"


"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\1\1.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\2\2.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\3\3.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\4\4.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\5\5.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\6\6.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\7\7.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\8\8.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\9\9.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\10\10.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\11\11.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\12\12.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\13\13.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\14\14.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\15\15.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\16\16.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\17\17.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\18\18.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\19\19.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\20\20.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\21\21.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\22\22.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\23\23.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\24\24.vmx"

"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\30\30.vmx"