vmrun deleteVM "E:/Virtual Machine/1/1.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/1/1.vmx" linked -cloneName="1"
vmrun deleteVM "E:/Virtual Machine/2/2.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/2/2.vmx" linked -cloneName="2"
vmrun deleteVM "E:/Virtual Machine/3/3.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/3/3.vmx" linked -cloneName="3"
vmrun deleteVM "E:/Virtual Machine/4/4.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/4/4.vmx" linked -cloneName="4"
vmrun deleteVM "E:/Virtual Machine/5/5.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/5/5.vmx" linked -cloneName="5"
vmrun deleteVM "E:/Virtual Machine/6/6.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/6/6.vmx" linked -cloneName="6"
vmrun deleteVM "E:/Virtual Machine/7/7.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/7/7.vmx" linked -cloneName="7"
vmrun deleteVM "E:/Virtual Machine/8/8.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/8/8.vmx" linked -cloneName="8"
vmrun deleteVM "E:/Virtual Machine/9/9.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/9/9.vmx" linked -cloneName="9"
vmrun deleteVM "E:/Virtual Machine/10/10.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/10/10.vmx" linked -cloneName="10"
vmrun deleteVM "E:/Virtual Machine/11/11.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/11/11.vmx" linked -cloneName="11"
vmrun deleteVM "E:/Virtual Machine/12/12.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/12/12.vmx" linked -cloneName="12"
vmrun deleteVM "E:/Virtual Machine/13/13.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/13/13.vmx" linked -cloneName="13"
vmrun deleteVM "E:/Virtual Machine/14/14.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/14/14.vmx" linked -cloneName="14"
vmrun deleteVM "E:/Virtual Machine/15/15.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/15/15.vmx" linked -cloneName="15"
