"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN1\1.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN2\2.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN3\3.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN4\4.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN5\5.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN6\6.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN7\7.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN8\8.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN9\9.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN10\10.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN11\11.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN12\12.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN13\13.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN14\14.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN15\15.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN16\16.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN17\17.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN18\18.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN19\19.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN20\20.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN21\21.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN22\22.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN23\23.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN24\24.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN25\25.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN26\26.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN27\27.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN28\28.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN29\29.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN30\30.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN31\31.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN32\32.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN33\33.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN34\34.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN35\35.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN36\36.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN37\37.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN38\38.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN39\39.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\LN40\40.vmx"


"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN1\1.vmx" linked -cloneName="LN1"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN2\2.vmx" linked -cloneName="LN2"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN3\3.vmx" linked -cloneName="LN3"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN4\4.vmx" linked -cloneName="LN4"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN5\5.vmx" linked -cloneName="LN5"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN6\6.vmx" linked -cloneName="LN6"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN7\7.vmx" linked -cloneName="LN7"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN8\8.vmx" linked -cloneName="LN8"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN9\9.vmx" linked -cloneName="LN9"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN10\10.vmx" linked -cloneName="LN10"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN11\11.vmx" linked -cloneName="LN11"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN12\12.vmx" linked -cloneName="LN12"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN13\13.vmx" linked -cloneName="LN13"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN14\14.vmx" linked -cloneName="LN14"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN15\15.vmx" linked -cloneName="LN15"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN16\16.vmx" linked -cloneName="LN16"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN17\17.vmx" linked -cloneName="LN17"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN18\18.vmx" linked -cloneName="LN18"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN19\19.vmx" linked -cloneName="LN19"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN20\20.vmx" linked -cloneName="LN20"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN21\21.vmx" linked -cloneName="LN21"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN22\22.vmx" linked -cloneName="LN22"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN23\23.vmx" linked -cloneName="LN23"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN24\24.vmx" linked -cloneName="LN24"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN25\25.vmx" linked -cloneName="LN25"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN26\26.vmx" linked -cloneName="LN26"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN27\27.vmx" linked -cloneName="LN27"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN28\28.vmx" linked -cloneName="LN28"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN29\29.vmx" linked -cloneName="LN29"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN30\30.vmx" linked -cloneName="LN30"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN31\31.vmx" linked -cloneName="LN31"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN32\32.vmx" linked -cloneName="LN32"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN33\33.vmx" linked -cloneName="LN33"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN34\34.vmx" linked -cloneName="LN34"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN35\35.vmx" linked -cloneName="LN35"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN36\36.vmx" linked -cloneName="LN36"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN37\37.vmx" linked -cloneName="LN37"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN38\38.vmx" linked -cloneName="LN38"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN39\39.vmx" linked -cloneName="LN39"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\LN40\40.vmx" linked -cloneName="LN40"

"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN1\1.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN2\2.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN3\3.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN4\4.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN5\5.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN6\6.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN7\7.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN8\8.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN9\9.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN10\10.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN11\11.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN12\12.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN13\13.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN14\14.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN15\15.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN16\16.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN17\17.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN18\18.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN19\19.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN20\20.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN21\21.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN22\22.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\LN23\23.vmx"