"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux1\1.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux2\2.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux3\3.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux4\4.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux5\5.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux6\6.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux7\7.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux8\8.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux9\9.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux10\10.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux11\11.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux12\12.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux13\13.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux14\14.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux15\15.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux16\16.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux17\17.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux18\18.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux19\19.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux20\20.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux21\21.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux22\22.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux23\23.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux24\24.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux25\25.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux26\26.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux27\27.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux28\28.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux29\29.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux30\30.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux31\31.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux32\32.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux33\33.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux34\34.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux35\35.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux36\36.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux37\37.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux38\38.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux39\39.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" deleteVM "E:\Virtual Machine\Linux40\40.vmx"


"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux1\1.vmx" linked -cloneName="1"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux2\2.vmx" linked -cloneName="2"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux3\3.vmx" linked -cloneName="3"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux4\4.vmx" linked -cloneName="4"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux5\5.vmx" linked -cloneName="5"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux6\6.vmx" linked -cloneName="6"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux7\7.vmx" linked -cloneName="7"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux8\8.vmx" linked -cloneName="8"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux9\9.vmx" linked -cloneName="9"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux10\10.vmx" linked -cloneName="10"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux11\11.vmx" linked -cloneName="11"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux12\12.vmx" linked -cloneName="12"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux13\13.vmx" linked -cloneName="13"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux14\14.vmx" linked -cloneName="14"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux15\15.vmx" linked -cloneName="15"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux16\16.vmx" linked -cloneName="16"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux17\17.vmx" linked -cloneName="17"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux18\18.vmx" linked -cloneName="18"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux19\19.vmx" linked -cloneName="19"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux20\20.vmx" linked -cloneName="20"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux21\21.vmx" linked -cloneName="21"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux22\22.vmx" linked -cloneName="22"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux23\23.vmx" linked -cloneName="23"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux24\24.vmx" linked -cloneName="24"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux25\25.vmx" linked -cloneName="25"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux26\26.vmx" linked -cloneName="26"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux27\27.vmx" linked -cloneName="27"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux28\28.vmx" linked -cloneName="28"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux29\29.vmx" linked -cloneName="29"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux30\30.vmx" linked -cloneName="30"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux31\31.vmx" linked -cloneName="31"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux32\32.vmx" linked -cloneName="32"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux33\33.vmx" linked -cloneName="33"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux34\34.vmx" linked -cloneName="34"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux35\35.vmx" linked -cloneName="35"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux36\36.vmx" linked -cloneName="36"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux37\37.vmx" linked -cloneName="37"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux38\38.vmx" linked -cloneName="38"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux39\39.vmx" linked -cloneName="39"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" clone "E:\Virtual Machine\Ubuntu\ubuntu.vmx" "E:\Virtual Machine\Linux40\40.vmx" linked -cloneName="40"

"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux1\1.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux2\2.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux3\3.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux4\4.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux5\5.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux6\6.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux7\7.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux8\8.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux9\9.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux10\10.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux11\11.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux12\12.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux13\13.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux14\14.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux15\15.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux16\16.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux17\17.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux18\18.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux19\19.vmx"
"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" start "E:\Virtual Machine\Linux20\20.vmx"