vmrun deleteVM "E:/Virtual Machine/L1/1.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L1/1.vmx" linked -cloneName="1"
vmrun deleteVM "E:/Virtual Machine/L2/2.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L2/2.vmx" linked -cloneName="2"
vmrun deleteVM "E:/Virtual Machine/L3/3.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L3/3.vmx" linked -cloneName="3"
vmrun deleteVM "E:/Virtual Machine/L4/4.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L4/4.vmx" linked -cloneName="4"
vmrun deleteVM "E:/Virtual Machine/L5/5.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L5/5.vmx" linked -cloneName="5"
vmrun deleteVM "E:/Virtual Machine/L6/6.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L6/6.vmx" linked -cloneName="6"
vmrun deleteVM "E:/Virtual Machine/L7/7.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L7/7.vmx" linked -cloneName="7"
vmrun deleteVM "E:/Virtual Machine/L8/8.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L8/8.vmx" linked -cloneName="8"
vmrun deleteVM "E:/Virtual Machine/L9/9.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L9/9.vmx" linked -cloneName="9"
vmrun deleteVM "E:/Virtual Machine/L10/10.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L10/10.vmx" linked -cloneName="10"
vmrun deleteVM "E:/Virtual Machine/L11/11.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L11/11.vmx" linked -cloneName="11"
vmrun deleteVM "E:/Virtual Machine/L12/12.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L12/12.vmx" linked -cloneName="12"
vmrun deleteVM "E:/Virtual Machine/L13/13.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L13/13.vmx" linked -cloneName="13"
vmrun deleteVM "E:/Virtual Machine/L14/14.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L14/14.vmx" linked -cloneName="14"
vmrun deleteVM "E:/Virtual Machine/L15/15.vmx"
vmrun clone "E:/Virtual Machine/Ubuntu/Ubuntu.vmx" "E:/Virtual Machine/L15/15.vmx" linked -cloneName="15"
