vmrun deleteVM "E:/Virtual Machine/1/1.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/1/1.vmx" linked -cloneName="1"
vmrun deleteVM "E:/Virtual Machine/2/2.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/2/2.vmx" linked -cloneName="2"
vmrun deleteVM "E:/Virtual Machine/3/3.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/3/3.vmx" linked -cloneName="3"
vmrun deleteVM "E:/Virtual Machine/4/4.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/4/4.vmx" linked -cloneName="4"
vmrun deleteVM "E:/Virtual Machine/5/5.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/5/5.vmx" linked -cloneName="5"
vmrun deleteVM "E:/Virtual Machine/6/6.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/6/6.vmx" linked -cloneName="6"
vmrun deleteVM "E:/Virtual Machine/7/7.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/7/7.vmx" linked -cloneName="7"
vmrun deleteVM "E:/Virtual Machine/8/8.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/8/8.vmx" linked -cloneName="8"
vmrun deleteVM "E:/Virtual Machine/9/9.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/9/9.vmx" linked -cloneName="9"
vmrun deleteVM "E:/Virtual Machine/10/10.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/10/10.vmx" linked -cloneName="10"
vmrun deleteVM "E:/Virtual Machine/11/11.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/11/11.vmx" linked -cloneName="11"
vmrun deleteVM "E:/Virtual Machine/12/12.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/12/12.vmx" linked -cloneName="12"
vmrun deleteVM "E:/Virtual Machine/13/13.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/13/13.vmx" linked -cloneName="13"
vmrun deleteVM "E:/Virtual Machine/14/14.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/14/14.vmx" linked -cloneName="14"
vmrun deleteVM "E:/Virtual Machine/15/15.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/15/15.vmx" linked -cloneName="15"
vmrun deleteVM "E:/Virtual Machine/16/16.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/16/16.vmx" linked -cloneName="16"
vmrun deleteVM "E:/Virtual Machine/17/17.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/17/17.vmx" linked -cloneName="17"
vmrun deleteVM "E:/Virtual Machine/18/18.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/18/18.vmx" linked -cloneName="18"
vmrun deleteVM "E:/Virtual Machine/19/19.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/19/19.vmx" linked -cloneName="19"
vmrun deleteVM "E:/Virtual Machine/20/20.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/20/20.vmx" linked -cloneName="20"
vmrun deleteVM "E:/Virtual Machine/21/21.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/21/21.vmx" linked -cloneName="21"
vmrun deleteVM "E:/Virtual Machine/22/22.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/22/22.vmx" linked -cloneName="22"
vmrun deleteVM "E:/Virtual Machine/23/23.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/23/23.vmx" linked -cloneName="23"
vmrun deleteVM "E:/Virtual Machine/24/24.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/24/24.vmx" linked -cloneName="24"
vmrun deleteVM "E:/Virtual Machine/25/25.vmx"
vmrun clone "E:/Virtual Machine/May Ao Chuan/Windows 7 x64.vmx" "E:/Virtual Machine/25/25.vmx" linked -cloneName="25"
